=== markwedding/piedmont_furnishings/salesreport.dtd
<!ELEMENT salesreport (sale+, totalprice)>
<!ELEMENT sale (ordernumber, customerid, agentid, date, status, product+)>
<!ELEMENT ordernumber (#PCDATA)>
<!ELEMENT customerid (#PCDATA)>
<!ELEMENT agentid (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT product (itemnumber, quantity, price, total)>
<!ELEMENT itemnumber (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT totalprice (#PCDATA)>

=== markwedding/piedmont_furnishings/salesReports/SalesReport_2016-08-25_20-48-50.xml
<?xml version="1.0"?>
<!DOCTYPE salesreport SYSTEM "salesreport.dtd">

<salesreport>
	<sale>
		<ordernumber>102</ordernumber>
		<customerid>99</customerid>
		<agentid>1</agentid>
		<date>7/20/11</date>
		<status>complete</status>
		<product>
			<itemnumber>BC501</itemnumber>
			<quantity>1</quantity>
			<price>$700.00</price>
			<total>$700.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>103</ordernumber>
		<customerid>234</customerid>
		<agentid>1</agentid>
		<date>7/20/11</date>
		<status>complete</status>
		<product>
			<itemnumber>BB501</itemnumber>
			<quantity>3</quantity>
			<price>$600.00</price>
			<total>$1,800.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>104</ordernumber>
		<customerid>190</customerid>
		<agentid>1</agentid>
		<date>7/25/11</date>
		<status>complete</status>
		<product>
			<itemnumber>BW501</itemnumber>
			<quantity>1</quantity>
			<price>$1,300.00</price>
			<total>$1,300.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>105</ordernumber>
		<customerid>164</customerid>
		<agentid>6</agentid>
		<date>7/25/11</date>
		<status>complete</status>
		<product>
			<itemnumber>BB501</itemnumber>
			<quantity>1</quantity>
			<price>$600.00</price>
			<total>$600.00</total>
		</product>
		<product>
			<itemnumber>LB101</itemnumber>
			<quantity>2</quantity>
			<price>$200.00</price>
			<total>$400.00</total>
		</product>
		<product>
			<itemnumber>LE202</itemnumber>
			<quantity>1</quantity>
			<price>$1,200.00</price>
			<total>$1,200.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>106</ordernumber>
		<customerid>34</customerid>
		<agentid>4</agentid>
		<date>7/28/11</date>
		<status>complete</status>
		<product>
			<itemnumber>BC501</itemnumber>
			<quantity>2</quantity>
			<price>$700.00</price>
			<total>$1,400.00</total>
		</product>
		<product>
			<itemnumber>BW501</itemnumber>
			<quantity>1</quantity>
			<price>$1,300.00</price>
			<total>$1,300.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>107</ordernumber>
		<customerid>29</customerid>
		<agentid>1</agentid>
		<date>7/29/11</date>
		<status>complete</status>
		<product>
			<itemnumber>BB501</itemnumber>
			<quantity>1</quantity>
			<price>$600.00</price>
			<total>$600.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>108</ordernumber>
		<customerid>1</customerid>
		<agentid>3</agentid>
		<date>7/31/11</date>
		<status>complete</status>
		<product>
			<itemnumber>DB301</itemnumber>
			<quantity>2</quantity>
			<price>$1,400.00</price>
			<total>$2,800.00</total>
		</product>
		<product>
			<itemnumber>DT301</itemnumber>
			<quantity>2</quantity>
			<price>$1,000.00</price>
			<total>$2,000.00</total>
		</product>
		<product>
			<itemnumber>DC301A</itemnumber>
			<quantity>4</quantity>
			<price>$300.00</price>
			<total>$1,200.00</total>
		</product>
		<product>
			<itemnumber>DC301B</itemnumber>
			<quantity>8</quantity>
			<price>$250.00</price>
			<total>$2,000.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>109</ordernumber>
		<customerid>253</customerid>
		<agentid>2</agentid>
		<date>8/3/11</date>
		<status>complete</status>
		<product>
			<itemnumber>BW501</itemnumber>
			<quantity>1</quantity>
			<price>$1,300.00</price>
			<total>$1,300.00</total>
		</product>
		<product>
			<itemnumber>DB301</itemnumber>
			<quantity>1</quantity>
			<price>$1,400.00</price>
			<total>$1,400.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>110</ordernumber>
		<customerid>33</customerid>
		<agentid>2</agentid>
		<date>8/5/11</date>
		<status>complete</status>
		<product>
			<itemnumber>DB301</itemnumber>
			<quantity>1</quantity>
			<price>$1,400.00</price>
			<total>$1,400.00</total>
		</product>
		<product>
			<itemnumber>BB602</itemnumber>
			<quantity>1</quantity>
			<price>$650.00</price>
			<total>$650.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>111</ordernumber>
		<customerid>162</customerid>
		<agentid>4</agentid>
		<date>8/5/11</date>
		<status>complete</status>
		<product>
			<itemnumber>LE202</itemnumber>
			<quantity>2</quantity>
			<price>$1,200.00</price>
			<total>$2,400.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>112</ordernumber>
		<customerid>227</customerid>
		<agentid>3</agentid>
		<date>8/6/11</date>
		<status>complete</status>
		<product>
			<itemnumber>LB202</itemnumber>
			<quantity>2</quantity>
			<price>$300.00</price>
			<total>$600.00</total>
		</product>
		<product>
			<itemnumber>LE101</itemnumber>
			<quantity>1</quantity>
			<price>$1,100.00</price>
			<total>$1,100.00</total>
		</product>
		<product>
			<itemnumber>BC603</itemnumber>
			<quantity>1</quantity>
			<price>$900.00</price>
			<total>$900.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>113</ordernumber>
		<customerid>144</customerid>
		<agentid>2</agentid>
		<date>8/7/11</date>
		<status>complete</status>
		<product>
			<itemnumber>LB101</itemnumber>
			<quantity>1</quantity>
			<price>$200.00</price>
			<total>$200.00</total>
		</product>
		<product>
			<itemnumber>DB301</itemnumber>
			<quantity>1</quantity>
			<price>$1,400.00</price>
			<total>$1,400.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>114</ordernumber>
		<customerid>75</customerid>
		<agentid>5</agentid>
		<date>8/7/11</date>
		<status>complete</status>
		<product>
			<itemnumber>DB301</itemnumber>
			<quantity>2</quantity>
			<price>$1,400.00</price>
			<total>$2,800.00</total>
		</product>
		<product>
			<itemnumber>LE202</itemnumber>
			<quantity>1</quantity>
			<price>$1,200.00</price>
			<total>$1,200.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>115</ordernumber>
		<customerid>222</customerid>
		<agentid>2</agentid>
		<date>8/11/11</date>
		<status>complete</status>
		<product>
			<itemnumber>LE101</itemnumber>
			<quantity>2</quantity>
			<price>$1,100.00</price>
			<total>$2,200.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>116</ordernumber>
		<customerid>233</customerid>
		<agentid>6</agentid>
		<date>8/11/11</date>
		<status>complete</status>
		<product>
			<itemnumber>DB301</itemnumber>
			<quantity>1</quantity>
			<price>$1,400.00</price>
			<total>$1,400.00</total>
		</product>
		<product>
			<itemnumber>DC301B</itemnumber>
			<quantity>4</quantity>
			<price>$250.00</price>
			<total>$1,000.00</total>
		</product>
		<product>
			<itemnumber>DC301A</itemnumber>
			<quantity>2</quantity>
			<price>$300.00</price>
			<total>$600.00</total>
		</product>
		<product>
			<itemnumber>DT301</itemnumber>
			<quantity>1</quantity>
			<price>$1,000.00</price>
			<total>$1,000.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>117</ordernumber>
		<customerid>233</customerid>
		<agentid>4</agentid>
		<date>8/12/11</date>
		<status>complete</status>
		<product>
			<itemnumber>BC501</itemnumber>
			<quantity>1</quantity>
			<price>$700.00</price>
			<total>$700.00</total>
		</product>
		<product>
			<itemnumber>LE203</itemnumber>
			<quantity>1</quantity>
			<price>$1,400.00</price>
			<total>$1,400.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>118</ordernumber>
		<customerid>14</customerid>
		<agentid>4</agentid>
		<date>8/12/11</date>
		<status>complete</status>
		<product>
			<itemnumber>BC501</itemnumber>
			<quantity>2</quantity>
			<price>$700.00</price>
			<total>$1,400.00</total>
		</product>
		<product>
			<itemnumber>LE101</itemnumber>
			<quantity>2</quantity>
			<price>$1,100.00</price>
			<total>$2,200.00</total>
		</product>
	</sale>
	<sale>
		<ordernumber>119</ordernumber>
		<customerid>9</customerid>
		<agentid>2</agentid>
		<date>8/15/11</date>
		<status>complete</status>
		<product>
			<itemnumber>LE203</itemnumber>
			<quantity>1</quantity>
			<price>$1,400.00</price>
			<total>$1,400.00</total>
		</product>
	</sale>
	<totalprice>$45,950.00</totalprice>
</salesreport>
